apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/training-operator/manifests/overlays/kubeflow?ref=v1.3.0

images:
- name: kubeflow/training-operator
  newName: public.ecr.aws/j1r0q0g6/training/training-operator
  newTag: "a1a0c188de17e0914bd7adfa79d16052276bffb1"
