apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=aab9542f8b3354f0940945c4295b67622f0af296 # tag=v2.1.1

patchesStrategicMerge:
- patches/configmap-patch.yaml

images:
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.30.0
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.1.6
- name: haproxy
  newName: haproxy
  newTag: 2.4.7-alpine
- name: redis
  newName: redis
  newTag: 6.2.6-alpine
