apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=a408e299ffa743213df3aa9135bf7945644ec936 # tag=v2.1.7

patchesStrategicMerge:
- patches/configmap-patch.yaml

images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.1.8
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.30.2
- name: redis
  newName: redis
  newTag: 6.2.6-alpine
- name: haproxy
  newName: haproxy
  newTag: 2.5.0-alpine
