apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.3.2

patchesStrategicMerge:
- patches/configmap-patch.yaml
