apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authorization-policy.yaml
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=1e9535ec06cae3823c33f29fc7890df9d32fcaf9 # tag=v1.4

patchesStrategicMerge:
- enable-sidecar.yaml
- spawner_ui_config.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newTag: v1.4
