apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authorization-policy.yaml
- https://github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=v1.6.0

patchesStrategicMerge:
- enable-sidecar.yaml
- spawner_ui_config.yaml
