# TODO: Use ExternalSecret with Google Cloud Secret Manager
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: auth
stringData:
  client-id: <<__external_secret_name.auth.oidc_client_id__>>
  client-secret: <<__external_secret_name.auth.oidc_client_secret__>>
  cookie-secret: <<__external_secret_name.auth.oidc_cookie_secret__>>
