apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    iam.gke.io/gcp-service-account: <<__gcp.cloud_dns_service_account__>>@<<__gcp.project_id__>>.iam.gserviceaccount.com
