apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "T2CeZ4unC+1RdZ6p01mqrcOyWzZxdW4h7V/9ccfRkDbW+39iqP71LbPby1nJKkvs\notbPChkiMQfacmWXSeRSRiYrRs6KCEr/ANGivui+ch+wBZQiC1ycq2Jgpwcnao5a\nL68IOV+oYnfn52BSPJVBXvm3YEoZlPVsye8HsyMFc98="
