apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "obKnxfDPOOmBN4vvELOaTS8ENfDW49Ml6+kS6sy/4DbxeFFWT4tXavBbaeWnpt1I\nSe9zf/xtV82u8HaKvAoEc+Yxrs8b3w6RadcVVxF8c3vtIILiWTE+rqmcJ91mVyOW\nJZpXXtAQ9Ldmx2ovtCLIS0PBzzk83Es34YRoGEJNyM8="
