apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoflow/argoflow
    targetRevision: HEAD
    path: distribution/kubeflow/common/dex-istio
    kustomize:
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
