apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.53.0
    chart: jaeger
    helm:
      parameters:
      - name: collector.service.zipkin.port
        value: "9411"
      - name: storage.type
        value: elasticsearch
      - name: provisionDataStore.cassandra
        value: "false"
      - name: provisionDataStore.elasticsearch
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
