apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorboards-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haoxins/argoflow-gcp
    targetRevision: master
    path: distribution/kubeflow/notebooks/tensorboard-controller
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
