apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: kubeflow-ingressgateway-certs
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
  commonName: <<__subdomain_dashboard__>>.<<__domain__>>
  dnsNames:
    - <<__subdomain_dashboard__>>.<<__domain__>>
