apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=d6bb86946845d5a0fc8c13dc5ede39eecf0f47fb # tag=v2.1.0-rc3

patchesStrategicMerge:
- configmap-patch.yaml
- add-custom-kustomize.yaml

images:
- name: ghcr.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.30.0
  # digest: sha256:63fc6ee14bcf1868ebfba90885aec76597e0f27bc8e89d1fd238b1f2ee3dea6e
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.1.0-rc3
  # digest: sha256:616cfb7dcd5b9e30a0b13982ca3cd43b8e3b3803f455a3f4265ba39030b21f2e
- name: haproxy
  newName: haproxy
  newTag: 2.4.2-alpine
  # digest: sha256:01eccc111d352dd77175b078d62078a4ce2f31256047980da4ebda8fa87a5ce7
- name: redis
  newName: redis
  newTag: 6.2.5-alpine
  # digest: sha256:fc856014691d52258a64ab4ef05bf835ce416eb552576264d98309ec92949aba
