apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-local-gateway.yaml
  - deny-all-authorizationpolicy.yaml
  - ingress-certificate.yaml
  # - kubeflow-cluster-roles.yaml
  - kubeflow-gateway.yaml
