apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  ingress.class: "istio.ingress.networking.knative.dev"
  domainTemplate: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  httpProtocol: "Redirected"
