apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
  - github.com/kubeflow/manifests/common/dex/overlays/istio

patchesStrategicMerge:
  - configmap-patch.yaml

images:
  - name: quay.io/dexidp/dex
    newName: ghcr.io/dexidp/dex
    newTag: v2.30.0
    # digest: sha256:63fc6ee14bcf1868ebfba90885aec76597e0f27bc8e89d1fd238b1f2ee3dea6e
