apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/jetstack/cert-manager/releases/download/v1.9.0/cert-manager.yaml
- cluster-issuers.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --cluster-issuer-ambient-credentials=true
  target:
    kind: Deployment
    name: cert-manager
